### ISSUE TITLE
how to install FASTPAGI?

### ISSUE THREAD

**Issue by sanderdabio** [marcelog/FastPAGI#1]
Hello Marcelo!

I am not able to configure FastAGI.
PAGI my application works fine.
I know it's my deficiency, but will you could explain a more complete example. Its framework is excellent and do not want to abandon it.

Excuse my English because I'm from Brazil and do not write very well.

Thank you.

Alex Simas

**Comment by marcelog** [comment]
Hey :)

Since this is not an issue per se, let me close it, and you can drop me an email, with all the details and the specific questions, or issues you may have. The more detailed the better :) Also, take a look at the readme, that has the needed instructions (and we can work on improving it if something's missing)

Cheers!
